development:
  sessions:
    default:
      uri: mongodb://heroku_app8697484:9vk7ntfismff29ubdo20l1csv6@dbh70.mongolab.com:27707/heroku_app8697484
      options:
        skip_version_check: true
        safe: true
        identity_map_enabled: true

production:
  sessions:
    default:
      uri: mongodb://heroku_app8697484:9vk7ntfismff29ubdo20l1csv6@dbh70.mongolab.com:27707/heroku_app8697484
      options:
        skip_version_check: true
        safe: true
        identity_map_enabled: true


